# Generated by Django 3.1.7 on 2021-08-29 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='fruit',
            fields=[
                ('genus', models.CharField(max_length=150)),
                ('name', models.CharField(max_length=150)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('family', models.CharField(max_length=150)),
                ('order', models.CharField(max_length=150)),
                ('carbohydrates', models.FloatField()),
                ('protein', models.FloatField()),
                ('fat', models.FloatField()),
                ('calories', models.FloatField()),
                ('sugar', models.FloatField()),
                ('image', models.CharField(max_length=556)),
            ],
        ),
    ]
